name: novo_projeto
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  dart_jsonwebtoken: ^2.14.1
  flutter:
    sdk: flutter
  flutter_masked_text2: ^0.9.1
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.3.2
  sqflite: ^2.3.3+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

